easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Objectif
        - App\Entity\Training
        - App\Entity\Users
        - App\Entity\Coach
        - App\Entity\Admin
