easy_admin:
    entities:
        Coach:
            class: App\Entity\Coach
            list:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'image', type: 'image', base_path: '%app.path.coach_images%' }
                    - { property: 'name', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'bio', type: 'text' }
                    - { property: 'training' }
            show:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'image', type: 'image', base_path: '%app.path.coach_images%' }
                    - { property: 'name', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'bio', type: 'text' }
                    - { property: 'training' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'name' }
                    - { property: 'lastname' }
                    - { property: 'email' }
                    - { property: 'bio' }
                    - { property: 'training' }
        Training:
            class: App\Entity\Training
            list:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'title', type: 'string' }
                    - { property: 'day', type: 'date' }
                    - { property: 'hour', type: 'time' }
                    - { property: 'periode', type: 'string' }
                    - { property: 'intensite', type: 'integer' }
                    - { property: 'coach' }
            show:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'title', type: 'string' }
                    - { property: 'day', type: 'date' }
                    - { property: 'hour', type: 'time' }
                    - { property: 'periode', type: 'string' }
                    - { property: 'intensite', type: 'integer' }
                    - { property: 'coach', type: 'string' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'day' }
                    - { property: 'hour' }
                    - { property: 'periode' }
                    - { property: 'intensite' }
                    - { property: 'coach' }
        Users:
            class: App\Entity\Users
            list:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'image', type: 'image', base_path: '%app.path.users_images%' }
                    - { property: 'username', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'password', type: 'string' }
                    - { property: 'training' }
            show:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'image', type: 'image', base_path: '%app.path.users_images%' }
                    - { property: 'username', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'password', type: 'string' }
                    - { property: 'training' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'username' }
                    - { property: 'lastname' }
                    - { property: 'email' }
                    - { property: 'password' }
                    - { property: 'training' }
        Admin:
            class: App\Entity\Admin
            list:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'name', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'password', type: 'string' }
            show:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'name', type: 'string' }
                    - { property: 'lastname', type: 'string' }
                    - { property: 'email', type: 'string' }
                    - { property: 'password', type: 'string' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'lastname' }
                    - { property: 'email' }
                    - { property: 'password' }
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'title', type: 'string' }
                    - { property: 'day', type: 'date' }
                    - { property: 'hour', type: 'time' }
                    - { property: 'description', type: 'text' }
                    - { property: 'isCanceled', type: 'boolean' }
            show:
                fields:
                    - { property: 'id', type: 'integer' }
                    - { property: 'title', type: 'string' }
                    - { property: 'day', type: 'date' }
                    - { property: 'hour', type: 'time' }
                    - { property: 'description', type: 'text' }
                    - { property: 'isCanceled', type: 'boolean' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'day' }
                    - { property: 'hour' }
                    - { property: 'description' }
                    - { property: 'isCanceled' }