security:
    providers:
        in_memory:
            memory:
                users:
                    lucky: { password: luke, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: true
            http_basic: false
        main:
            anonymous: true
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /index
            logout:
                path:   /logout
                target: /



    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }